# Generated by Django 5.1.6 on 2025-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=30, unique=True)),
                ('blog_title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Tech', 'Science & Technology'), ('Food', 'Food'), ('Lifestyle', 'Lifestyle')], default='Tech', max_length=20)),
                ('content', models.TextField()),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
