# Generated by Django 5.1.6 on 2025-02-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mriic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_id',
            new_name='Blog_id',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image',
            new_name='Blog_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='Blog_title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='Created_at',
        ),
    ]
